//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitTracker.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user187_dbEntities : DbContext
    {
        public user187_dbEntities()
            : base("name=user187_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diplom_Habit> Diplom_Habit { get; set; }
        public virtual DbSet<Diplom_Note> Diplom_Note { get; set; }
        public virtual DbSet<Diplom_Type_habit> Diplom_Type_habit { get; set; }
        public virtual DbSet<Diplom_UserRole> Diplom_UserRole { get; set; }
        public virtual DbSet<Diplom_Users> Diplom_Users { get; set; }
        public virtual DbSet<Diplom_Users_Habit> Diplom_Users_Habit { get; set; }
        public virtual DbSet<Note_Type> Note_Type { get; set; }
    }
}
