//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitTracker.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diplom_Users_Habit
    {
        public int ID_Users { get; set; }
        public string ID_Habit { get; set; }
        public Nullable<System.DateTime> Date_start { get; set; }
        public Nullable<int> Attempt { get; set; }
        public Nullable<int> Amount_of_day { get; set; }
        public int Record { get; set; }
        public int ID_Users_Habit { get; set; }
    
        public virtual Diplom_Habit Diplom_Habit { get; set; }
        public virtual Diplom_Users Diplom_Users { get; set; }
    }
}
