//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitTracker.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diplom_Note
    {
        public int ID_Note { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_Users { get; set; }
        public Nullable<int> ID_Type_Note { get; set; }
        public Nullable<bool> CheckPoint { get; set; }
    
        public virtual Diplom_Users Diplom_Users { get; set; }
        public virtual Note_Type Note_Type { get; set; }
    }
}
